<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Jadwal;
use App\Models\User;
use App\Models\Shift;
use Carbon\Carbon;

class JadwalJanuariSeeder extends Seeder
{
    public function run()
    {
        // 1. Ambil 4 karyawan (non-admin)
        $karyawans = User::where('is_admin', false)->take(4)->get();

        // Jika user kurang dari 4, buat dummy baru (opsional)
        if ($karyawans->count() < 4) {
            $this->command->error("Pastikan Anda memiliki minimal 4 user non-admin di database.");
            return;
        }

        // 2. Ambil semua shift yang tersedia
        $shifts = Shift::all();
        
        if ($shifts->isEmpty()) {
            $this->command->error("Data Shift kosong. Silakan isi table shifts terlebih dahulu.");
            return;
        }

        // Identifikasi shift berdasarkan nama untuk logika sederhana
        $shiftPagi = $shifts->filter(fn($s) => str_contains(strtoupper($s->nama_shift), 'PAGI'))->first();
        $shiftSiang = $shifts->filter(fn($s) => str_contains(strtoupper($s->nama_shift), 'SIANG'))->first();
        $shiftMalam = $shifts->filter(fn($s) => str_contains(strtoupper($s->nama_shift), 'MALAM'))->first();
        $shiftLibur = $shifts->filter(fn($s) => str_contains(strtoupper($s->nama_shift), 'LIBUR'))->first();

        $listShift = [$shiftPagi, $shiftSiang, $shiftMalam, $shiftLibur];
        // Bersihkan array dari null jika ada shift yang tidak ditemukan
        $listShift = array_filter($listShift);

        // 3. Loop 31 hari di Januari 2026
        for ($day = 1; $day <= 31; $day++) {
            $tanggal = Carbon::create(2026, 1, $day);

            foreach ($karyawans as $karyawan) {
                // Ambil shift secara acak dari list yang tersedia
                $shiftTerpilih = $listShift[array_rand($listShift)];

                Jadwal::updateOrCreate(
                    [
                        'user_id' => $karyawan->id,
                        'tanggal' => $tanggal->format('Y-m-d'),
                    ],
                    [
                        'shift_id' => $shiftTerpilih->id,
                        'keterangan' => 'Generated by Seeder',
                    ]
                );
            }
        }

        $this->command->info("Berhasil membuat jadwal untuk 4 karyawan selama bulan Januari 2026.");
    }
}